version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # Persiste los datos localmente en una carpeta oculta del proyecto
      - ./.postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres_db
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

